# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d59fe8a86045611aad3891e2e40832ff22523472ec59ef94603685f76502050210dcb8e72a99da8f6fe17273dd1bf0cf5ccd87c94296a9c9296651c5541ed8f

test:
  secret_key_base: 4597ef1e8f77e1f59e7862809c87ae6f480a3e55b56c08751d4734e25f599c43006974f71dae9c549f38b5b635f207038558843d58d3957e34bc0d0da28f905c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
